version: '3'
services:
  indexer:
    build:
      context: ../
      args:
        - target=explorer
    command: ./explorer -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - INDEXER_ENABLED=true
    network_mode: "host"
  eth1indexer:
    build: 
      context: ../
      args:
        - target=eth1indexer
    command: ./eth1indexer -config /app/config.yml -blocks.concurrency 1 -blocks.tracemode 'geth' -data.concurrency 1 --balances.enabled
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  rewards-exporter:
    build: 
      context: ../
      args:
        - target=rewards-exporter
    command: ./rewards-exporter -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  statistics:
    build: 
      context: ../
      args:
        - target=stats
    command: ./statistics -config /app/config.yml --charts.enabled --graffiti.enabled -validators.enabled
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  frontend-data-updater:
    build: 
      context: ../
      args:
        - target=frontend-data-updater
    command: ./frontend-data-updater -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    network_mode: "host"
  frontend:
    build: 
      context: ../
      args:
        - target=explorer
    command: ./explorer -config /app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    environment:
      - FRONTEND_ENABLED=true
    network_mode: "host"